site_name: django Notes
nav:
  - index: index.md
  - into: into.md
  - urls: urls.md
  - deploy: deploy.md
  - template: template.md
  - settings: settings.md
  - other: other.md
  - log: log.md
theme:
  name: 'material'
  palette:
    primary: 'Light Green'
    accent: 'Teal'
    language: 'zh'
    feature:
      tabs: true
markdown_extensions:
  - admonition
  - codehilite
